// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// find_sequence
int find_sequence(RawVector buffer, RawVector pattern);
RcppExport SEXP burrp_find_sequence(SEXP bufferSEXP, SEXP patternSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type buffer(bufferSEXP);
    Rcpp::traits::input_parameter< RawVector >::type pattern(patternSEXP);
    rcpp_result_gen = Rcpp::wrap(find_sequence(buffer, pattern));
    return rcpp_result_gen;
END_RCPP
}
